### ISSUE TITLE
Gradle 'XYZReader' project refresh failed

### ISSUE THREAD

**Issue by Mardoqueu** [mvescovo/xyzreader#7]
Error:Could not find com.android.tools.build:gradle:2.2.3.
Searched in the following locations:
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.jar
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.jar
Required by:
    :xyzreader-master:unspecified

**Comment by mvescovo** [comment]
Gradle has been updated. No errors now.
